// dashboard/src/lib/components/ModelPickerGroup.svelte
<script lang="ts">
  interface ModelInfo {
    id: string;
    name?: string;
    storage_size_megabytes?: number;
    base_model?: string;
    quantization?: string;
    supports_tensor?: boolean;
    capabilities?: string[];
    family?: string;
    is_custom?: boolean;
  }

  interface ModelGroup {
    id: string;
    name: string;
    capabilities: string[];
    family: string;
    variants: ModelInfo[];
    smallestVariant: ModelInfo;
    hasMultipleVariants: boolean;
  }

  type DownloadAvailability = {
    available: boolean;
    nodeNames: string[];
    nodeIds: string[];
  };
  type ModelFitStatus = "fits_now" | "fits_cluster_capacity" | "too_large";

  type ModelPickerGroupProps = {
    group: ModelGroup;
    isExpanded: boolean;
    isFavorite: boolean;
    isHighlighted?: boolean;
    selectedModelId: string | null;
    canModelFit: (id: string) => boolean;
    getModelFitStatus: (id: string) => ModelFitStatus;
    onToggleExpand: () => void;
    onSelectModel: (modelId: string) => void;
    onToggleFavorite: (baseModelId: string) => void;
    onShowInfo: (group: ModelGroup) => void;
    downloadStatusMap?: Map<string, DownloadAvailability>;
    launchedAt?: number;
    instanceStatuses?: Record<string, { status: string; statusClass: string }>;
    mode?: "launch" | "store-download";
  };

  let {
    group,
    isExpanded,
    isFavorite,
    isHighlighted = false,
    selectedModelId,
    canModelFit,
    getModelFitStatus,
    onToggleExpand,
    onSelectModel,
    onToggleFavorite,
    onShowInfo,
    downloadStatusMap,
    launchedAt,
    instanceStatuses = {},
    mode = "launch",
  }: ModelPickerGroupProps = $props();

  // Group-level download status: show if any variant is downloaded
  const groupDownloadStatus = $derived.by(() => {
    if (!downloadStatusMap || downloadStatusMap.size === 0) return undefined;
    // Return the first available entry (prefer "available" ones)
    for (const avail of downloadStatusMap.values()) {
      if (avail.available) return avail;
    }
    return downloadStatusMap.values().next().value;
  });

  // Format storage size
  function formatSize(mb: number | undefined): string {
    if (!mb) return "";
    if (mb >= 1024) {
      return `${(mb / 1024).toFixed(0)}GB`;
    }
    return `${mb}MB`;
  }

  function timeAgo(ts: number): string {
    const seconds = Math.floor((Date.now() - ts) / 1000);
    if (seconds < 60) return "just now";
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    return `${days}d ago`;
  }

  // Check if any variant can fit
  const anyVariantFits = $derived(
    group.variants.some((v) => canModelFit(v.id)),
  );
  // Check if any variant has an active instance (ready, loading, downloading)
  const anyVariantHasInstance = $derived(
    instanceStatuses
      ? group.variants.some((v) => instanceStatuses[v.id] != null)
      : false,
  );
  const groupFitStatus = $derived.by((): ModelFitStatus => {
    let hasClusterCapacityOnly = false;
    for (const variant of group.variants) {
      const fitStatus = getModelFitStatus(variant.id);
      if (fitStatus === "fits_now") {
        return "fits_now";
      }
      if (fitStatus === "fits_cluster_capacity") {
        hasClusterCapacityOnly = true;
      }
    }
    return hasClusterCapacityOnly ? "fits_cluster_capacity" : "too_large";
  });

  function getSizeClassForFitStatus(fitStatus: ModelFitStatus): string {
    switch (fitStatus) {
      case "fits_now":
        return "text-white/40";
      case "fits_cluster_capacity":
        return "text-orange-400/80";
      case "too_large":
        return "text-red-400/70";
    }
  }

  // Check if this group's model is currently selected (for single-variant groups)
  const isMainSelected = $derived(
    !group.hasMultipleVariants &&
      group.variants.some((v) => v.id === selectedModelId),
  );

  // Group-level instance status: show the "best" status across all variants
  const groupInstanceStatus = $derived.by(() => {
    if (!instanceStatuses) return null;
    const readyStatuses = ["READY", "LOADED", "RUNNING"];
    const loadingStatuses = ["LOADING", "WARMING UP"];
    let bestStatus: { status: string; statusClass: string } | null = null;
    for (const variant of group.variants) {
      const s = instanceStatuses[variant.id];
      if (!s) continue;
      if (readyStatuses.includes(s.status)) return s; // Ready is best
      if (loadingStatuses.includes(s.status) || s.status === "DOWNLOADING") {
        bestStatus = s;
      }
    }
    return bestStatus;
  });
</script>

<div
  data-model-ids={group.variants.map((v) => v.id).join(" ")}
  class="border-b border-white/5 last:border-b-0 {!anyVariantFits &&
  !anyVariantHasInstance
    ? 'opacity-50'
    : ''} {isHighlighted ? 'model-just-added' : ''}"
>
  <!-- Main row -->
  <div
    class="flex items-center gap-2 px-3 py-2.5 transition-colors {anyVariantFits ||
    anyVariantHasInstance
      ? 'hover:bg-white/5 cursor-pointer'
      : 'cursor-not-allowed'} {isMainSelected
      ? 'bg-exo-yellow/10 border-l-2 border-exo-yellow'
      : 'border-l-2 border-transparent'}"
    onclick={() => {
      if (mode === "store-download") {
        onToggleExpand();
      } else if (group.hasMultipleVariants) {
        onToggleExpand();
      } else {
        const modelId = group.variants[0]?.id;
        if (modelId && (canModelFit(modelId) || instanceStatuses[modelId])) {
          onSelectModel(modelId);
        }
      }
    }}
    role="button"
    tabindex="0"
    onkeydown={(e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        if (mode === "store-download") {
          onToggleExpand();
        } else if (group.hasMultipleVariants) {
          onToggleExpand();
        } else {
          const modelId = group.variants[0]?.id;
          if (modelId && (canModelFit(modelId) || instanceStatuses[modelId])) {
            onSelectModel(modelId);
          }
        }
      }
    }}
  >
    <!-- Expand/collapse chevron (for groups with variants) -->
    {#if group.hasMultipleVariants}
      <svg
        class="w-4 h-4 text-white/40 transition-transform duration-200 flex-shrink-0 {isExpanded
          ? 'rotate-90'
          : ''}"
        viewBox="0 0 24 24"
        fill="currentColor"
      >
        <path d="M8.59 16.59L13.17 12 8.59 7.41 10 6l6 6-6 6-1.41-1.41z" />
      </svg>
    {:else}
      <div class="w-4 flex-shrink-0"></div>
    {/if}

    <!-- Model name -->
    <div class="flex-1 min-w-0">
      <div class="flex items-center gap-2">
        <span class="font-mono text-sm text-white truncate">
          {group.name}
        </span>
        <!-- Capability icons -->
        {#each group.capabilities.filter((c) => c !== "text") as cap}
          {#if cap === "thinking"}
            <svg
              class="w-3.5 h-3.5 text-white/40 flex-shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              title="Supports Thinking"
            >
              <path
                d="M12 2a7 7 0 0 0-7 7c0 2.38 1.19 4.47 3 5.74V17a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-2.26c1.81-1.27 3-3.36 3-5.74a7 7 0 0 0-7-7zM9 20h6M10 22h4"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          {:else if cap === "code"}
            <svg
              class="w-3.5 h-3.5 text-white/40 flex-shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              title="Supports code generation"
            >
              <path
                d="M16 18l6-6-6-6M8 6l-6 6 6 6"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          {:else if cap === "vision"}
            <svg
              class="w-3.5 h-3.5 text-white/40 flex-shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              title="Supports image input"
            >
              <path
                d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <circle cx="12" cy="12" r="3" />
            </svg>
          {:else if cap === "image_gen"}
            <svg
              class="w-3.5 h-3.5 text-white/40 flex-shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              title="Supports image generation"
            >
              <rect
                x="3"
                y="3"
                width="18"
                height="18"
                rx="2"
                ry="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <circle cx="8.5" cy="8.5" r="1.5" />
              <path
                d="M21 15l-5-5L5 21"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          {:else if cap === "image_edit"}
            <svg
              class="w-3.5 h-3.5 text-white/40 flex-shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              title="Supports image editing"
            >
              <path
                d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
              <path
                d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          {/if}
        {/each}
      </div>
    </div>

    <!-- Size indicator (smallest variant) -->
    {#if !group.hasMultipleVariants && group.smallestVariant?.storage_size_megabytes}
      {@const singleVariantFitStatus = getModelFitStatus(
        group.smallestVariant.id,
      )}
      <span
        class="text-xs font-mono flex-shrink-0 {getSizeClassForFitStatus(
          singleVariantFitStatus,
        )}"
      >
        {formatSize(group.smallestVariant.storage_size_megabytes)}
      </span>
    {/if}

    <!-- Variant count with size range -->
    {#if group.hasMultipleVariants}
      {@const sizes = group.variants
        .map((v) => v.storage_size_megabytes || 0)
        .filter((s) => s > 0)
        .sort((a, b) => a - b)}
      <span
        class="text-xs font-mono flex-shrink-0 {getSizeClassForFitStatus(
          groupFitStatus,
        )}"
      >
        {group.variants.length} variants{#if sizes.length >= 2}{" "}({formatSize(
            sizes[0],
          )}-{formatSize(sizes[sizes.length - 1])}){/if}
      </span>
    {/if}

    <!-- Time ago (for recent models) -->
    {#if launchedAt}
      <span class="text-xs font-mono text-white/20 flex-shrink-0">
        {timeAgo(launchedAt)}
      </span>
    {/if}

    <!-- Download availability indicator -->
    {#if groupDownloadStatus && groupDownloadStatus.nodeIds.length > 0}
      <span
        class="flex-shrink-0"
        title={groupDownloadStatus.available
          ? `Ready — downloaded on ${groupDownloadStatus.nodeNames.join(", ")}`
          : `Downloaded on ${groupDownloadStatus.nodeNames.join(", ")} (may need more nodes)`}
      >
        <svg
          class="w-4 h-4"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path
            class="text-white/40"
            d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
          />
          <path class="text-green-400" d="m9 13 2 2 4-4" />
        </svg>
      </span>
    {/if}

    <!-- Instance status badge -->
    {#if groupInstanceStatus}
      {#if groupInstanceStatus.status === "READY" || groupInstanceStatus.status === "LOADED" || groupInstanceStatus.status === "RUNNING"}
        <span class="flex-shrink-0" title="Running">
          <svg
            class="w-3 h-3 text-green-400"
            viewBox="0 0 12 12"
            fill="currentColor"
          >
            <circle cx="6" cy="6" r="5" />
          </svg>
        </span>
      {:else if groupInstanceStatus.status === "DOWNLOADING"}
        <span class="flex-shrink-0 animate-pulse" title="Downloading">
          <svg
            class="w-3.5 h-3.5 text-blue-400"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
        </span>
      {:else if groupInstanceStatus.status === "LOADING" || groupInstanceStatus.status === "WARMING UP"}
        <span class="flex-shrink-0 animate-pulse" title="Loading">
          <svg
            class="w-3 h-3 text-yellow-400"
            viewBox="0 0 12 12"
            fill="currentColor"
          >
            <circle cx="6" cy="6" r="5" />
          </svg>
        </span>
      {/if}
    {/if}

    <!-- Check mark if selected (single-variant) -->
    {#if isMainSelected}
      <svg
        class="w-4 h-4 text-exo-yellow flex-shrink-0"
        viewBox="0 0 24 24"
        fill="currentColor"
      >
        <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z" />
      </svg>
    {/if}

    <!-- Favorite star -->
    <button
      type="button"
      class="p-1 rounded hover:bg-white/10 transition-colors flex-shrink-0"
      onclick={(e) => {
        e.stopPropagation();
        onToggleFavorite(group.id);
      }}
      title={isFavorite ? "Remove from favorites" : "Add to favorites"}
    >
      {#if isFavorite}
        <svg
          class="w-4 h-4 text-amber-400"
          viewBox="0 0 24 24"
          fill="currentColor"
        >
          <path
            d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"
          />
        </svg>
      {:else}
        <svg
          class="w-4 h-4 text-white/30 hover:text-white/50"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path
            d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"
          />
        </svg>
      {/if}
    </button>

    <!-- Info button -->
    <button
      type="button"
      class="p-1 rounded hover:bg-white/10 transition-colors flex-shrink-0"
      onclick={(e) => {
        e.stopPropagation();
        onShowInfo(group);
      }}
      title="View model details"
    >
      <svg
        class="w-4 h-4 text-white/30 hover:text-white/50"
        viewBox="0 0 24 24"
        fill="currentColor"
      >
        <path
          d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"
        />
      </svg>
    </button>
    {#if mode === "store-download" && !group.hasMultipleVariants}
      <button
        type="button"
        class="p-1 rounded hover:bg-exo-yellow/10 transition-colors flex-shrink-0"
        onclick={(e) => {
          e.stopPropagation();
          const modelId = group.variants[0]?.id;
          if (modelId) onSelectModel(modelId);
        }}
        title="Download to store"
      >
        <svg
          class="w-4 h-4 text-exo-yellow/60 hover:text-exo-yellow"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M12 3v12" />
          <path d="M7 12l5 5 5-5" />
          <path d="M5 21h14" />
        </svg>
      </button>
    {/if}
  </div>

  <!-- Expanded variants -->
  {#if isExpanded && group.hasMultipleVariants}
    <div class="bg-black/20 border-t border-white/5">
      {#each group.variants as variant}
        {@const fitStatus = getModelFitStatus(variant.id)}
        {@const modelCanFit = canModelFit(variant.id)}
        {@const variantHasInstance = instanceStatuses[variant.id] != null}
        {@const isSelected = selectedModelId === variant.id}
        <div
          class="w-full flex items-center gap-3 px-3 py-2 pl-10 hover:bg-white/5 transition-colors text-left {!modelCanFit &&
          !variantHasInstance
            ? 'opacity-50 cursor-not-allowed'
            : 'cursor-pointer'} {isSelected
            ? 'bg-exo-yellow/10 border-l-2 border-exo-yellow'
            : 'border-l-2 border-transparent'}"
          role="button"
          tabindex="0"
          onclick={() => {
            if (
              mode !== "store-download" &&
              (modelCanFit || variantHasInstance)
            ) {
              onSelectModel(variant.id);
            }
          }}
          onkeydown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              e.preventDefault();
              if (mode !== "store-download" && modelCanFit) {
                onSelectModel(variant.id);
              }
            }
          }}
        >
          <!-- Quantization badge -->
          <span
            class="text-xs font-mono px-1.5 py-0.5 rounded bg-white/10 text-white/70 flex-shrink-0"
          >
            {variant.quantization || "default"}
          </span>

          <!-- Size -->
          <span
            class="text-xs font-mono flex-1 {getSizeClassForFitStatus(
              fitStatus,
            )}"
          >
            {formatSize(variant.storage_size_megabytes)}
          </span>

          <!-- Download indicator for this variant -->
          {#if downloadStatusMap?.get(variant.id)}
            {@const variantDl = downloadStatusMap.get(variant.id)}
            {#if variantDl}
              <span
                class="flex-shrink-0"
                title={`Downloaded on ${variantDl.nodeNames.join(", ")}`}
              >
                <svg
                  class="w-3.5 h-3.5"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path
                    class="text-white/40"
                    d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
                  />
                  <path class="text-green-400" d="m9 13 2 2 4-4" />
                </svg>
              </span>
            {/if}
          {/if}

          <!-- Instance status badge -->
          {#if instanceStatuses[variant.id]}
            {@const instStatus = instanceStatuses[variant.id]}
            {#if instStatus.status === "READY" || instStatus.status === "LOADED" || instStatus.status === "RUNNING"}
              <span class="flex-shrink-0" title="Running">
                <svg
                  class="w-3 h-3 text-green-400"
                  viewBox="0 0 12 12"
                  fill="currentColor"
                >
                  <circle cx="6" cy="6" r="5" />
                </svg>
              </span>
            {:else if instStatus.status === "DOWNLOADING"}
              <span class="flex-shrink-0 animate-pulse" title="Downloading">
                <svg
                  class="w-3.5 h-3.5 text-blue-400"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
              </span>
            {:else if instStatus.status === "LOADING" || instStatus.status === "WARMING UP"}
              <span class="flex-shrink-0 animate-pulse" title="Loading">
                <svg
                  class="w-3 h-3 text-yellow-400"
                  viewBox="0 0 12 12"
                  fill="currentColor"
                >
                  <circle cx="6" cy="6" r="5" />
                </svg>
              </span>
            {/if}
          {/if}

          <!-- Check mark if selected -->
          {#if isSelected}
            <svg
              class="w-4 h-4 text-exo-yellow"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <path
                d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z"
              />
            </svg>
          {/if}

          <!-- Info button -->
          <button
            type="button"
            class="p-1 rounded hover:bg-white/10 transition-colors flex-shrink-0"
            onclick={(e) => {
              e.stopPropagation();
              onShowInfo({
                id: variant.id,
                name: variant.name || variant.id,
                capabilities: group.capabilities,
                family: group.family,
                variants: [variant],
                smallestVariant: variant,
                hasMultipleVariants: false,
              });
            }}
            title="View variant details"
          >
            <svg
              class="w-4 h-4 text-white/30 hover:text-white/50"
              viewBox="0 0 24 24"
              fill="currentColor"
            >
              <path
                d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"
              />
            </svg>
          </button>
          {#if mode === "store-download"}
            <button
              type="button"
              class="p-1 rounded hover:bg-exo-yellow/10 transition-colors flex-shrink-0"
              onclick={(e) => {
                e.stopPropagation();
                onSelectModel(variant.id);
              }}
              title="Download to store"
            >
              <svg
                class="w-4 h-4 text-exo-yellow/60 hover:text-exo-yellow"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M12 3v12" />
                <path d="M7 12l5 5 5-5" />
                <path d="M5 21h14" />
              </svg>
            </button>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .model-just-added {
    animation: highlightFade 4s ease-out forwards;
  }

  @keyframes highlightFade {
    0%,
    40% {
      background-color: rgba(20, 83, 45, 0.25);
      box-shadow: inset 0 0 0 1px rgba(74, 222, 128, 0.4);
    }
    100% {
      background-color: transparent;
      box-shadow: none;
    }
  }
</style>

// dashboard-react/src/components/models/ModelPickerGroup.tsx
import styled, { css, keyframes } from 'styled-components';
import type {
  ModelGroup,
  ModelInfo,
  ModelFitStatus,
  DownloadAvailability,
  InstanceStatus,
  PickerMode,
} from '../../types/models';
import { formatBytes } from '../../utils/format';

export interface ModelPickerGroupProps {
  group: ModelGroup;
  isExpanded: boolean;
  isFavorite: boolean;
  isHighlighted?: boolean;
  selectedModelId: string | null;
  canModelFit: (id: string) => boolean;
  getModelFitStatus: (id: string) => ModelFitStatus;
  onToggleExpand: () => void;
  onSelectModel: (modelId: string) => void;
  onToggleFavorite: (groupId: string) => void;
  onShowInfo?: (group: ModelGroup) => void;
  downloadStatusMap?: Map<string, DownloadAvailability>;
  launchedAt?: number;
  instanceStatuses?: Record<string, InstanceStatus>;
  mode?: PickerMode;
}

/* ---------- helpers ---------- */

function sizeText(mb?: number): string {
  if (!mb) return '';
  return formatBytes(mb * 1024 * 1024);
}

function fitColor(status: ModelFitStatus): string {
  if (status === 'fits_now') return 'rgba(255,255,255,0.9)';
  if (status === 'fits_cluster_capacity') return '#fb923c';
  return '#f87171';
}

function timeAgo(ts: number): string {
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

const CAPABILITY_ICONS: Record<string, string> = {
  thinking: '🧠',
  code: '💻',
  vision: '👁',
  image_gen: '🎨',
  image_edit: '✏️',
};

function bestInstanceStatus(
  variants: ModelInfo[],
  statuses?: Record<string, InstanceStatus>,
): InstanceStatus | null {
  if (!statuses) return null;
  const order = ['ready', 'loading', 'downloading'];
  let best: InstanceStatus | null = null;
  let bestRank = Infinity;
  for (const v of variants) {
    const s = statuses[v.id];
    if (!s) continue;
    const rank = order.indexOf(s.statusClass);
    if (rank !== -1 && rank < bestRank) {
      bestRank = rank;
      best = s;
    }
  }
  return best;
}

/* ---------- styles ---------- */

const glowAnim = keyframes`
  0%, 100% { box-shadow: 0 0 4px rgba(34,197,94,0.4); }
  50%      { box-shadow: 0 0 12px rgba(34,197,94,0.7); }
`;

const Row = styled.div<{ $disabled: boolean; $highlighted: boolean }>`
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border-radius: ${({ theme }) => theme.radii.md};
  cursor: pointer;
  transition: background 0.15s;
  user-select: none;

  &:hover {
    background: ${({ theme }) => theme.colors.surfaceHover};
  }

  ${({ $disabled }) =>
    $disabled &&
    css`
      opacity: 0.5;
      pointer-events: none;
    `}

  ${({ $highlighted }) =>
    $highlighted &&
    css`
      animation: ${glowAnim} 1.5s ease-in-out 3;
    `}
`;

const Chevron = styled.span<{ $open: boolean }>`
  font-size: 10px;
  color: ${({ theme }) => theme.colors.textMuted};
  transition: transform 0.15s;
  width: 14px;
  text-align: center;
  ${({ $open }) => $open && css`transform: rotate(90deg);`}
`;

const Name = styled.span`
  flex: 1;
  font-size: 13px;
  font-weight: 500;
  color: ${({ theme }) => theme.colors.text};
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
`;

const Caps = styled.span`
  font-size: 12px;
  margin-left: 4px;
`;

const Badge = styled.span<{ $color?: string }>`
  font-size: 11px;
  padding: 2px 6px;
  border-radius: ${({ theme }) => theme.radii.sm};
  background: ${({ theme }) => theme.colors.surfaceHover};
  color: ${({ $color, theme }) => $color ?? theme.colors.textSecondary};
`;

const StatusDot = styled.span<{ $class: string }>`
  width: 7px;
  height: 7px;
  border-radius: 50%;
  flex-shrink: 0;
  ${({ $class }) => {
    if ($class === 'ready') return css`background: #22c55e;`;
    if ($class === 'loading') return css`background: #eab308;`;
    if ($class === 'downloading') return css`background: #3b82f6;`;
    return css`background: #666;`;
  }}
`;

const FavStar = styled.button<{ $active: boolean }>`
  all: unset;
  cursor: pointer;
  font-size: 14px;
  color: ${({ $active }) => ($active ? '#fbbf24' : '#555')};
  transition: color 0.15s;
  &:hover {
    color: #fbbf24;
  }
`;

const InfoBtn = styled.button`
  all: unset;
  cursor: pointer;
  font-size: 12px;
  color: ${({ theme }) => theme.colors.textMuted};
  &:hover {
    color: ${({ theme }) => theme.colors.text};
  }
`;

const DownloadIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="2">
    <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);

const CheckMark = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="2.5">
    <polyline points="20 6 9 17 4 12" />
  </svg>
);

const VariantList = styled.div`
  padding: 4px 0 4px 32px;
  display: flex;
  flex-direction: column;
  gap: 2px;
`;

const VariantRow = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border-radius: ${({ theme }) => theme.radii.sm};
  cursor: pointer;
  font-size: 12px;
  color: ${({ theme }) => theme.colors.textSecondary};
  transition: background 0.15s;

  &:hover {
    background: ${({ theme }) => theme.colors.surfaceHover};
  }
`;

/* ---------- component ---------- */

export function ModelPickerGroup({
  group,
  isExpanded,
  isFavorite,
  isHighlighted = false,
  selectedModelId,
  canModelFit,
  getModelFitStatus,
  onToggleExpand,
  onSelectModel,
  onToggleFavorite,
  onShowInfo,
  downloadStatusMap,
  launchedAt,
  instanceStatuses,
  mode = 'launch',
}: ModelPickerGroupProps) {
  const { variants, hasMultipleVariants } = group;
  const singleVariant = !hasMultipleVariants ? variants[0] : null;

  const anyFits = variants.some((v) => canModelFit(v.id));
  const anyHasInstance = variants.some((v) => instanceStatuses?.[v.id]);
  const disabled = !anyFits && !anyHasInstance;

  const groupFit = variants.reduce<ModelFitStatus>((best, v) => {
    const s = getModelFitStatus(v.id);
    if (s === 'fits_now') return 'fits_now';
    if (s === 'fits_cluster_capacity' && best !== 'fits_now') return 'fits_cluster_capacity';
    return best;
  }, 'too_large');

  const groupDownload = variants.find((v) => downloadStatusMap?.get(v.id)?.available);
  const instanceStatus = bestInstanceStatus(variants, instanceStatuses);

  const isSelected = singleVariant ? selectedModelId === singleVariant.id : false;

  const caps = group.capabilities.filter((c) => c in CAPABILITY_ICONS);

  const handleRowClick = () => {
    if (singleVariant) {
      onSelectModel(singleVariant.id);
    } else {
      onToggleExpand();
    }
  };

  // Size display
  let sizeDisplay: React.ReactNode;
  if (hasMultipleVariants) {
    const smallest = sizeText(variants[0].storage_size_megabytes);
    const largest = sizeText(variants[variants.length - 1].storage_size_megabytes);
    sizeDisplay = (
      <Badge>
        {variants.length} variants{smallest && largest ? ` (${smallest}–${largest})` : ''}
      </Badge>
    );
  } else if (singleVariant?.storage_size_megabytes) {
    sizeDisplay = (
      <Badge $color={fitColor(groupFit)}>
        {sizeText(singleVariant.storage_size_megabytes)}
      </Badge>
    );
  }

  return (
    <div>
      <Row $disabled={disabled} $highlighted={isHighlighted} onClick={handleRowClick}>
        {/* Chevron */}
        {hasMultipleVariants ? (
          <Chevron $open={isExpanded}>▶</Chevron>
        ) : (
          <span style={{ width: 14 }} />
        )}

        {/* Name + caps */}
        <Name>
          {group.name}
          {caps.length > 0 && <Caps>{caps.map((c) => CAPABILITY_ICONS[c]).join('')}</Caps>}
        </Name>

        {/* Size */}
        {sizeDisplay}

        {/* Time ago */}
        {launchedAt != null && (
          <Badge>{timeAgo(launchedAt)}</Badge>
        )}

        {/* Download indicator */}
        {groupDownload && <DownloadIcon />}

        {/* Instance status dot */}
        {instanceStatus && <StatusDot $class={instanceStatus.statusClass} />}

        {/* Selected check */}
        {isSelected && <CheckMark />}

        {/* Favorite */}
        <FavStar
          $active={isFavorite}
          onClick={(e) => {
            e.stopPropagation();
            onToggleFavorite(group.id);
          }}
          title={isFavorite ? 'Remove from favorites' : 'Add to favorites'}
        >
          {isFavorite ? '★' : '☆'}
        </FavStar>

        {/* Info */}
        {onShowInfo && (
          <InfoBtn
            onClick={(e) => {
              e.stopPropagation();
              onShowInfo(group);
            }}
            title="Model info"
          >
            ⓘ
          </InfoBtn>
        )}
      </Row>

      {/* Expanded variants */}
      {isExpanded && hasMultipleVariants && (
        <VariantList>
          {variants.map((v) => {
            const vFit = getModelFitStatus(v.id);
            const vDownload = downloadStatusMap?.get(v.id);
            const vInstance = instanceStatuses?.[v.id];
            const vSelected = selectedModelId === v.id;

            return (
              <VariantRow key={v.id} onClick={() => onSelectModel(v.id)}>
                {v.quantization && <Badge>{v.quantization}</Badge>}
                <span style={{ color: fitColor(vFit), flex: 1 }}>
                  {sizeText(v.storage_size_megabytes)}
                </span>
                {vDownload?.available && <DownloadIcon />}
                {vInstance && <StatusDot $class={vInstance.statusClass} />}
                {vSelected && <CheckMark />}
              </VariantRow>
            );
          })}
        </VariantList>
      )}
    </div>
  );
}
